
const PROGRAM=[
{day:'Monday',kind:'strength',focus:'Full-Body Foundation Strength',time:'60 min',mission:'Build foundational whole-body strength through squat, hinge, push, posture, core, unilateral leg work, and loaded carries.',warm:['March in place — 1 minute','Bodyweight squats — 10','Hip hinges — 10','Cat-Cow — 8','Bird Dog — 6 each side','Arm circles — 15 forward / 15 backward','Band pull-aparts or scapular retractions — 15'],cool:['Doorway chest stretch — 30 sec each side','Kneeling hip-flexor stretch — 30 sec each side','Child’s Pose — 30–45 sec','Diaphragmatic breathing — 5 slow breaths'],ex:[
{name:'Goblet Squat',sets:4,reps:'6–8',rest:'90–120 sec',cue:'Brace, sit between the hips, knees track over toes, drive through the whole foot.'},
{name:'Dumbbell Romanian Deadlift',sets:3,reps:'8',rest:'90 sec',cue:'Push hips back, keep dumbbells close, neutral spine, squeeze glutes to stand.'},
{name:'Reverse Dumbbell Lunge',sets:3,reps:'8 each leg',rest:'75 sec',cue:'Step back under control, stay tall, drive through the front foot.',alt:'Step-Up if lunges are uncomfortable'},
{name:'Dumbbell Floor Press',sets:3,reps:'8–10',rest:'90 sec',cue:'Wrists over elbows, lightly touch upper arms to floor, press smoothly.'},
{name:'Standing Dumbbell Overhead Press',sets:3,reps:'8',rest:'75 sec',cue:'Brace, ribs down, press overhead without leaning back.'},
{name:'Farmer Carry',sets:3,time:'45–60 sec',rest:'60 sec',cue:'Stand tall, shoulders level, controlled steps, breathe normally.'},
{name:'Band Face Pull',sets:2,reps:'12–15',rest:'45 sec',cue:'Pull toward forehead, elbows high, avoid shrugging.',alt:'Dumbbell rear-delt fly'},
{name:'Pallof Press',sets:2,reps:'10 each side',rest:'30–45 sec',cue:'Keep hips square and resist rotation.',alt:'Suitcase carry'},
{name:'Bird Dog',sets:2,reps:'8 each side',rest:'30 sec',cue:'Reach long, keep hips level, avoid arching.'}
]},
{day:'Tuesday',kind:'strength',focus:'Upper Pull, Posture, Arms & Core',time:'45 min',mission:'Develop upper-back, lat, grip and biceps strength while reinforcing posture and trunk stability.',warm:['March in place — 1 minute','Band pull-aparts — 15','Arm circles — 15 each direction','Cat-Cow — 8','Bird Dog — 6 each side'],cool:['Doorway chest stretch — 30 sec each side','Open-book thoracic rotation — 6 each side','Diaphragmatic breathing — 5 breaths'],ex:[
{name:'One-Arm Dumbbell Row',sets:4,reps:'8–10 each side',rest:'75 sec',cue:'Pull elbow toward back pocket, pause, do not twist.'},
{name:'Band Lat Pulldown',sets:3,reps:'10–12',rest:'60 sec',cue:'Drive elbows toward ribs, chest lifted, return slowly.'},
{name:'Hammer Curl',sets:3,reps:'10–12',rest:'45 sec',cue:'Elbows close, no swinging, lower slowly.'},
{name:'Rear Delt Fly',sets:3,reps:'12–15',rest:'45 sec',cue:'Soft elbows, lift with rear shoulders, avoid shrugging.',alt:'Band face pull'},
{name:'Band Pull-Apart',sets:2,reps:'15',rest:'30 sec',cue:'Shoulders down, squeeze upper back, return slowly.',alt:'Prone Y-T-W raise'},
{name:'Dead Bug',sets:2,reps:'8–10 each side',rest:'30 sec',cue:'Keep ribs down and lower back steady as limbs extend.'},
{name:'Side Plank',sets:2,time:'30–45 sec each side',rest:'30 sec',cue:'Keep hips lifted and body aligned.'}
]},
{day:'Wednesday',kind:'strength',focus:'Lower Body & Posterior Chain Strength',time:'60 min',mission:'Build strong hips, glutes, hamstrings and legs while reinforcing spinal stability, balance, and carrying strength.',warm:['March in place — 1 minute','Hip hinges — 10','Bodyweight good mornings — 10','Mini-band lateral walk — 10 each direction','Cat-Cow — 8','Bird Dog — 6 each side','World’s greatest stretch — 5 each side'],cool:['Kneeling hip-flexor stretch — 30 sec each side','Figure-4 glute stretch — 30 sec each side','Child’s Pose — 30–45 sec','Diaphragmatic breathing — 5 breaths'],ex:[
{name:'Dumbbell Romanian Deadlift',sets:4,reps:'6–8',rest:'2 min',cue:'Brace, hips back, weights close, neutral spine, finish with glutes.'},
{name:'Bulgarian Split Squat',sets:3,reps:'8 each leg',rest:'90 sec',cue:'Stay tall, front knee tracks over toes, drive through front foot.'},
{name:'Step-Up',sets:3,reps:'8–10 each leg',rest:'75 sec',cue:'Use the lead leg, stand fully, lower slowly and under control.'},
{name:'Dumbbell Hip Thrust',sets:3,reps:'10–12',rest:'75 sec',cue:'Ribs down, drive through heels, pause and squeeze glutes at the top.',alt:'Glute Bridge'},
{name:'Suitcase Carry',sets:3,time:'45–60 sec each side',rest:'45 sec',cue:'Resist leaning, shoulders level, slow steps.'},
{name:'Pallof Press',sets:2,reps:'10 each side',rest:'30–45 sec',cue:'Brace, keep hips and shoulders square, and resist rotation.',alt:'Repeat Suitcase Carry if using dumbbells only'},
{name:'Rear Delt Fly',sets:2,reps:'12–15',rest:'45 sec',cue:'Lift from rear shoulders, keep neck relaxed, avoid shrugging.',alt:'Band face pull'},
{name:'Dead Bug',sets:2,reps:'10 each side',rest:'30 sec',cue:'Lower back gently down, exhale as limb extends.'},
{name:'Standing Calf Raise',sets:3,reps:'15–20',rest:'30–45 sec',cue:'Rise high, pause briefly, lower slowly through full range.'}
]},
{day:'Thursday',kind:'recovery',focus:'Recovery: Yoga, Yin Yoga & Optional Walking',time:'Recovery day',mission:'Recover from strength training with a general yoga practice, a separate yin-yoga practice, and optional walking or mobility work.',warm:['Choose the recovery activities that fit your body today. No strength warm-up is required.'],cool:['Finish feeling calmer, looser, and ready for Friday.'],ex:[
{name:'Yoga Practice',sets:1,time:'20–60 min',rest:'',cue:'Choose a yoga style that matches your energy and recovery needs for the day.',typeLabel:'Yoga type',typeOptions:['Gentle Vinyasa Yoga','Power Yoga','Restorative Yoga','Hatha / General Yoga','Other Yoga']},
{name:'Yin Yoga Practice',sets:1,time:'20–60 min',rest:'',cue:'Use sustained positions at a tolerable intensity and never force a joint.',typeLabel:'Yin type',typeOptions:['Yin Yoga','Restorative Yin Yoga','Gentle Yin Yoga','Other Yin Practice']},
{name:'Walking (Optional)',sets:1,time:'10–60 min',rest:'',cue:'Keep the pace conversational and restorative rather than demanding.'},
{name:'Mobility / Reset Work (Optional)',sets:1,time:'5–20 min',rest:'',cue:'Focus on areas that feel stiff, using slow, pain-free movement.'}
]},
{day:'Friday',kind:'strength',focus:'Upper Push, Posture, Arms & Calves',time:'45 min',mission:'Build upper-body pushing strength while maintaining shoulder balance, posture, arm strength, and lower-leg resilience.',warm:['March in place — 1 minute','Band pull-aparts — 15','Arm circles — 15 each direction','Shoulder rolls — 10 each direction','Scapular push-ups — 10'],cool:['Doorway chest stretch — 30 sec each side','Cross-body shoulder stretch — 30 sec each side','Standing calf stretch — 30 sec each side'],ex:[
{name:'Standing Dumbbell Overhead Press',sets:3,reps:'6–8',rest:'75–90 sec',cue:'Brace, keep ribs down, and press overhead without leaning back.'},
{name:'Push-Up Plus',sets:3,reps:'8–12',rest:'60–75 sec',cue:'Straight body line; at top push floor away to protract shoulder blades.',alt:'Incline push-up plus'},
{name:'Dumbbell Floor Press',sets:3,reps:'8–10',rest:'75 sec',cue:'Shoulders packed, wrists straight, controlled lowering.'},
{name:'Overhead Dumbbell Triceps Extension',sets:2,reps:'10–12',rest:'45 sec',cue:'Elbows mostly forward, ribs down, controlled lowering.'},
{name:'Alternating Dumbbell Curl',sets:2,reps:'10 each arm',rest:'45 sec',cue:'Elbows close, no swinging, control the eccentric.'},
{name:'Band Face Pull',sets:2,reps:'12–15',rest:'45 sec',cue:'Elbows high, pull toward forehead, avoid shrugging.',alt:'Rear-delt fly'},
{name:'Band External Rotation',sets:2,reps:'12–15 each arm',rest:'30 sec',cue:'Elbow tucked, rotate from shoulder, torso still.',alt:'Side-lying dumbbell external rotation'},
{name:'Standing Calf Raise',sets:3,reps:'15–20',rest:'30–45 sec',cue:'Rise high, pause, lower slowly through full range.'}
]},
{day:'Saturday',kind:'strength',focus:'Full-Body Functional Strength & Performance',time:'60 min',mission:'Integrate strength, coordination, stability, carries, balance, and whole-body movement into one comprehensive session.',warm:['March in place — 1 minute','Bodyweight squats — 10','Hip hinges — 10','World’s greatest stretch — 5 each side','Arm circles — 15 each direction','Bird Dog — 6 each side','Scapular push-ups — 10'],cool:['Figure-4 glute stretch — 30 sec each side','Doorway chest stretch — 30 sec each side','Child’s Pose — 30–45 sec','Diaphragmatic breathing — 5 breaths'],ex:[
{name:'Dumbbell Thruster',sets:4,reps:'6–8',rest:'90–120 sec',cue:'Controlled squat, drive through legs, finish overhead without arching.'},
{name:'Walking Dumbbell Lunge',sets:3,reps:'10 each leg',rest:'75 sec',cue:'Upright torso, controlled stride, push through front foot.'},
{name:'One-Arm Dumbbell Row',sets:3,reps:'8–10 each side',rest:'60–75 sec',cue:'Stable torso, elbow to hip, controlled return.'},
{name:'Incline or Standard Push-Up',sets:3,reps:'8–12',rest:'60 sec',cue:'Straight body line, controlled lowering, press floor away.'},
{name:'Farmer Carry',sets:3,time:'60 sec',rest:'60 sec',cue:'Tall posture, level shoulders, smooth breathing.'},
{name:'Partial Turkish Get-Up',sets:2,reps:'3 each side',rest:'60 sec',cue:'Move step by step and keep the shoulder stable.',alt:'Full Turkish Get-Up when ready'},
{name:'Renegade Row',sets:2,reps:'6–8 each side',rest:'60 sec',cue:'Keep hips square and row without twisting.',alt:'Plank dumbbell drag or One-Arm Row'},
{name:'Single-Leg Balance Reach',sets:2,reps:'8 each leg',rest:'30 sec',cue:'Reach slowly and return under control.'},
{name:'Bear Crawl',sets:2,time:'20–30 sec',rest:'45 sec',cue:'Keep knees low, hips level, and move opposite hand and foot together.'}
]},
{day:'Sunday',kind:'recovery',focus:'Recovery: Yoga, Yin Yoga & Optional Walking',time:'Recovery day',mission:'Restore your body and prepare for Monday with a general yoga practice, a separate yin-yoga practice, and optional walking or mobility work.',warm:['Choose the recovery activities that fit your energy, soreness, and schedule today.'],cool:['Finish feeling restored, with no sense of strain.'],ex:[
{name:'Yoga Practice',sets:1,time:'20–60 min',rest:'',cue:'Choose a yoga style that fits your energy while supporting recovery for Monday.',typeLabel:'Yoga type',typeOptions:['Gentle Vinyasa Yoga','Power Yoga','Restorative Yoga','Hatha / General Yoga','Other Yoga']},
{name:'Yin Yoga Practice',sets:1,time:'20–60 min',rest:'',cue:'Use sustained positions at a tolerable intensity and never force a joint.',typeLabel:'Yin type',typeOptions:['Yin Yoga','Restorative Yin Yoga','Gentle Yin Yoga','Other Yin Practice']},
{name:'Walking (Optional)',sets:1,time:'10–60 min',rest:'',cue:'Choose an easy pace that leaves you refreshed.'},
{name:'Mobility / Reset Work (Optional)',sets:1,time:'5–20 min',rest:'',cue:'Use slow, comfortable movement for stiff areas.'}
]}
]
const KEY='strengthTrackerLocalV1';let activeDay=0;let currentExercises=[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function isoToday(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}
function records(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
function setRecords(r){localStorage.setItem(KEY,JSON.stringify(r)); if(!cloudApplying) renderCloudState();}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function optionList(values,current='',blankLabel='—'){const cur=String(current??'');const vals=[...new Set(values.map(String))];if(cur&&!vals.includes(cur))vals.unshift(cur);return `<option value="">${blankLabel}</option>`+vals.map(v=>`<option value="${esc(v)}" ${v===cur?'selected':''}>${esc(v)}</option>`).join('')}
function weightOptions(current=''){const vals=[];for(let x=0;x<=100;x+=2.5)vals.push(Number.isInteger(x)?String(x):x.toFixed(1));for(let x=105;x<=200;x+=5)vals.push(String(x));return optionList(vals,current,'— lb —')}
function repOptions(current=''){return optionList(Array.from({length:31},(_,i)=>String(i)),current,'— reps —')}
function timeOptions(current=''){const vals=[];for(let x=5;x<=120;x+=5)vals.push(String(x));[150,180,240,300,360,420,480,600].forEach(x=>vals.push(String(x)));return optionList(vals,current,'— sec —')}
function setCountOptions(current='2'){return optionList(['1','2','3','4','5','6'],current,'— sets —')}
function nav(){ $$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.view));if(b.dataset.view==='dashboard')renderDashboard();if(b.dataset.view==='history')renderHistory();if(b.dataset.view==='progress')renderProgress();}); }
function renderDaybar(){daybar.innerHTML=PROGRAM.map((d,i)=>`<button class="daybtn ${i===activeDay?'active':''}" data-i="${i}"><b>${d.day}</b><span>${d.time} · ${d.ex.length} ${d.kind==='recovery'?'activities':'exercises'}</span></button>`).join('');$$('.daybtn').forEach(b=>b.onclick=()=>{activeDay=+b.dataset.i;renderWorkout(true)});}
const EXERCISE_LIBRARY=[
'Arnold Press','Assisted Pull-Up','Band External Rotation','Band High Row','Band Lat Pulldown','Band Pull-Apart','Bear Crawl','Bird Dog','Bodyweight Squat','Bottom-Up Carry','Bulgarian Split Squat','Chest-Supported Dumbbell Row','Chin Tuck','Close-Grip Push-Up','Cossack Squat','Cross-Body Hammer Curl','Dead Bug','Dumbbell Floor Press','Dumbbell Hip Thrust','Dumbbell Romanian Deadlift','Dumbbell Thruster','Farmer Carry','Farmer Carry on Toes','Glute Bridge','Glute Bridge March','Goblet Cyclist Squat','Goblet Squat','Half-Kneeling Dumbbell Press','Hammer Curl','Heel-to-Toe Walk','High Band Row','Incline Dumbbell Press','Incline Push-Up','Inverted Row','Lateral Lunge','Mini-Band Lateral Walk','Monster Walk','One-Arm Dumbbell Row','Overhead Dumbbell Triceps Extension','Overhead Carry','Pallof Press','Partial Turkish Get-Up','Plank','Plate Pinch Carry','Prone Y-T-W Raises','Pull-Up','Push-Up','Push-Up Plus','Rear Delt Fly','Renegade Row','Reverse Lunge','Reverse Snow Angel','Scapular Push-Up','Side Plank','Single-Leg Balance Reach','Single-Leg Calf Raise','Single-Leg Glute Bridge','Single-Leg Romanian Deadlift','Skater Step','Standing Band Row','Standing Calf Raise','Standing Dumbbell Overhead Press','Step-Down','Step-Up','Straight-Arm Band Pulldown','Suitcase Carry','Sumo Squat','Turkish Get-Up','Walking Dumbbell Lunge','Wall Slides','Z-Press'
];
function customExerciseOptions(selected=''){const today=new Set(PROGRAM[activeDay].ex.map(e=>e.name));const other=EXERCISE_LIBRARY.filter(n=>!today.has(n)).sort();const current=EXERCISE_LIBRARY.filter(n=>today.has(n)).sort();let html='<option value="">Select an exercise</option><optgroup label="Exercises not in today’s program">'+other.map(n=>`<option ${n===selected?'selected':''}>${esc(n)}</option>`).join('')+'</optgroup>';if(current.length)html+='<optgroup label="Already in today’s program">'+current.map(n=>`<option ${n===selected?'selected':''}>${esc(n)}</option>`).join('')+'</optgroup>';html+='<option value="__other__">Other — enter manually</option>';return html}
function refreshCustomSelectors(){document.querySelectorAll('.custom-form').forEach(form=>{const sel=form.querySelector('.customExercise'),chosen=sel.value;sel.innerHTML=customExerciseOptions(chosen);if(chosen&&[...sel.options].some(o=>o.value===chosen))sel.value=chosen;toggleManualName(form)})}
function toggleManualName(form){const isOther=form.querySelector('.customExercise').value==='__other__';form.querySelector('.manual-name').hidden=!isOther;if(!isOther)form.querySelector('.customName').value=''}
function baseExercises(){return PROGRAM[activeDay].ex.map((e,i)=>({...e,id:`base-${i}`,custom:false,complete:false,originalName:e.name,originalPrescription:{sets:e.sets,reps:e.reps||'',time:e.time||'',rest:e.rest||'',cue:e.cue||'',alt:e.alt||'',typeLabel:e.typeLabel||'',typeOptions:e.typeOptions||[]},selectedType:e.selectedType||'',substitutedFor:'',setData:Array.from({length:e.sets},()=>({weight:'',reps:'',time:'',notes:''}))}))}

function setHasData(s){return Boolean(String(s?.weight||'').trim()||String(s?.reps||'').trim()||String(s?.time||'').trim())}
function exerciseProgress(e){const total=Math.max(1,e.setData?.length||e.sets||1);const done=e.complete?total:(e.setData||[]).filter(setHasData).length;return {done:Math.min(done,total),total,percent:Math.round(Math.min(done,total)/total*100)}}
function workoutProgress(r){const ex=r?.exercises||[];const total=ex.reduce((n,e)=>n+exerciseProgress(e).total,0);const done=ex.reduce((n,e)=>n+exerciseProgress(e).done,0);return {done,total,percent:total?Math.round(done/total*100):0}}
function fullyCompleted(r){return workoutProgress(r).percent===100}
function hasWorkoutProgress(r){return workoutProgress(r).done>0}
function previousRecordFor(name){return records().filter(r=>r.date<workoutDate.value).sort((a,b)=>b.date.localeCompare(a.date)).flatMap(r=>r.exercises.filter(e=>e.name===name&&exerciseProgress(e).done>0).map(e=>({date:r.date,e}))).find(Boolean)}
function previousPerformance(name){const p=previousRecordFor(name);if(!p)return '';return `<div class="previous"><b>Last completed ${p.date}:</b> ${bestSummary(p.e)}</div>`}
function markEveryExercise(value){currentExercises.forEach(e=>e.complete=value);renderExercises();updateCompletion()}
function dateDiffDays(a,b){return Math.round((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000)}
function streakStats(){const dates=[...new Set(records().filter(hasWorkoutProgress).map(r=>r.date))].sort();if(!dates.length)return {current:0,longest:0};let longest=1,run=1;for(let i=1;i<dates.length;i++){if(dateDiffDays(dates[i-1],dates[i])===1)run++;else run=1;longest=Math.max(longest,run)}let current=0;const desc=[...dates].sort().reverse();const today=isoToday();if(desc[0]===today||dateDiffDays(desc[0],today)===1){current=1;for(let i=1;i<desc.length;i++){if(dateDiffDays(desc[i],desc[i-1])===1)current++;else break}}return {current,longest}}
function monthKey(d){return d.slice(0,7)}
function personalBests(limit=6){const best={};records().forEach(r=>r.exercises.filter(e=>exerciseProgress(e).done>0).forEach(e=>e.setData.filter(setHasData).forEach(s=>{const w=+s.weight||0,rep=parseFloat(s.reps)||0,t=parseFloat(s.time)||0,volume=w*rep;const score=w?1000000+w*1000+rep:t?500000+t:volume;const cur=best[e.name];if(!cur||score>cur.score)best[e.name]={name:e.name,date:r.date,w,rep,t,volume,score}})));return Object.values(best).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,limit)}
function renderDashboard(){
 const all=records(),today=isoToday(),ws=weekStart(today),month=monthKey(today),weekRecords=all.filter(r=>r.date>=ws),monthRecords=all.filter(r=>monthKey(r.date)===month),st=streakStats(),minutes=all.reduce((n,r)=>n+(+r.totalMinutes||0),0);
 const aggregate=list=>{const total=list.reduce((n,r)=>n+workoutProgress(r).total,0),done=list.reduce((n,r)=>n+workoutProgress(r).done,0);return {done,total,percent:total?Math.round(done/total*100):0}};
 const wp=aggregate(weekRecords),mp=aggregate(monthRecords);
 dashboardStats.innerHTML=`<div class="dash-stat"><span>This week’s set completion</span><b>${wp.percent}%</b><small>${wp.done}/${wp.total||0} sets across ${weekRecords.length} logged workout${weekRecords.length===1?'':'s'}</small></div><div class="dash-stat"><span>This month’s set completion</span><b>${mp.percent}%</b><small>${mp.done}/${mp.total||0} sets</small></div><div class="dash-stat"><span>Current training streak</span><b>${st.current} days</b><small>Any saved workout progress counts</small></div><div class="dash-stat"><span>Total training time</span><b>${minutes} min</b><small>From saved workout minutes</small></div>`;
 const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
 dashboardWeek.innerHTML=days.map((day,i)=>{const d=new Date(ws+'T12:00:00');d.setDate(d.getDate()+i);const ds=d.toISOString().slice(0,10),rec=all.find(r=>r.date===ds&&r.day===day),p=rec?workoutProgress(rec):null;return `<div class="week-cell ${p&&p.percent===100?'done':''}"><b>${day.slice(0,3)}</b><small>${ds.slice(5)}</small><div>${p?p.percent+'%':'—'}</div>${p?`<small>${p.done}/${p.total} sets</small>`:''}</div>`}).join('');
 const prs=personalBests();dashboardPRs.innerHTML=prs.length?prs.map(p=>`<div class="pr-card"><b>${esc(p.name)}</b><span>${p.w?p.w+' lb':p.t?p.t+' sec':p.rep?p.rep+' reps':'Recorded'} · ${p.date}</span></div>`).join(''):'<div class="empty">Personal bests will appear after performance data are saved.</div>'
}


function substitutionOptions(selected=''){
  const originalNames=new Set(PROGRAM[activeDay].ex.map(e=>e.name));
  const choices=EXERCISE_LIBRARY.filter(n=>!originalNames.has(n)).sort();
  let html='<option value="">Select a replacement</option>';
  html+=choices.map(n=>`<option value="${esc(n)}" ${n===selected?'selected':''}>${esc(n)}</option>`).join('');
  html+='<option value="__other__">Other — enter manually</option>';
  return html;
}
function applySubstitution(e,card){
  const sel=card.querySelector('.sub-select');
  const manual=card.querySelector('.sub-manual-input');
  const selected=sel.value;
  const replacement=selected==='__other__' ? manual.value.trim() : selected;
  if(!replacement){alert(selected==='__other__'?'Enter the replacement exercise name.':'Select a replacement exercise.');return;}
  if(!e.originalName)e.originalName=e.substitutedFor||e.name;
  if(!e.originalPrescription)e.originalPrescription={sets:e.setData?.length||e.sets||1,reps:e.reps||'',time:e.time||'',rest:e.rest||'',cue:e.cue||'',alt:e.alt||''};
  e.substitutedFor=e.originalName;
  e.name=replacement;
  e.cue='Perform the replacement with controlled technique and record any variation details in Notes.';
  e.alt=`Replacement for ${e.originalName}. Completed replacement sets count toward today’s programmed work.`;
  renderExercises();updateCompletion();
}
function restoreOriginal(e){
  if(!e.originalName)return;
  const p=e.originalPrescription||{};
  e.name=e.originalName;
  e.reps=p.reps||'';e.time=p.time||'';e.rest=p.rest||'';e.cue=p.cue||'';e.alt=p.alt||'';
  e.substitutedFor='';
  renderExercises();updateCompletion();
}
function displayExerciseName(e){return e.substitutedFor?`${e.name} (substituted for ${e.substitutedFor})`:e.name}
function normalizeSavedExercises(saved){
  const bases=baseExercises();
  if(!Array.isArray(saved)||saved.length===0)return bases;
  const used=new Set();
  const merged=bases.map((base,i)=>{
    const found=saved.find((x,j)=>!used.has(j)&&!x.custom&&(x.id===base.id||x.originalName===base.name||(!x.substitutedFor&&x.name===base.name)));
    if(!found)return base;
    const j=saved.indexOf(found);used.add(j);
    const mergedItem={...base,...found,id:base.id,custom:false,originalName:base.name,originalPrescription:base.originalPrescription};
    if(!Array.isArray(mergedItem.setData)||mergedItem.setData.length===0)mergedItem.setData=base.setData;
    return mergedItem;
  });
  saved.forEach((x,j)=>{if(x.custom&&!used.has(j))merged.push(x)});
  return merged;
}

function renderWorkout(reset=true){const d=PROGRAM[activeDay];dayTitle.textContent=`${d.day} — ${d.focus}`;mission.textContent=d.mission;summary.innerHTML=`<span class="pill">${d.time}</span><span class="pill">${d.ex.length} ${d.kind==='recovery'?'recovery activities':'programmed exercises'}</span><span class="pill">${d.kind==='recovery'?'Recovery tracking':'Set-level tracking'}</span>`;warmup.innerHTML=d.warm.map(x=>`<li>${esc(x)}</li>`).join('');cooldown.innerHTML=d.cool.map(x=>`<li>${esc(x)}</li>`).join('');renderDaybar();refreshCustomSelectors();if(reset){currentExercises=baseExercises();clearSessionFields()}renderExercises();updateCompletion();loadSaved(false)}
function renderExercises(){exerciseList.innerHTML=currentExercises.map((e,i)=>exerciseHTML(e,i)).join('');$$('.exercise').forEach((card,i)=>{const e=currentExercises[i];card.querySelector('.donecheck').onchange=ev=>{e.complete=ev.target.checked;card.classList.toggle('done',e.complete);updateCompletion()};card.querySelectorAll('.setrow').forEach((row,si)=>{['weight','reps','time','notes'].forEach(k=>{const el=row.querySelector('.'+k);const handler=ev=>{e.setData[si][k]=ev.target.value;updateCompletion()};el.oninput=handler;el.onchange=handler})});const typeSel=card.querySelector('.activityType');if(typeSel)typeSel.onchange=ev=>{e.selectedType=ev.target.value};card.querySelector('.addset').onclick=()=>{e.setData.push({weight:'',reps:'',time:'',notes:''});renderExercises();updateCompletion()};card.querySelector('.removeset').onclick=()=>{if(e.setData.length>1)e.setData.pop();renderExercises();updateCompletion()};const del=card.querySelector('.deleteExercise');if(del)del.onclick=()=>{currentExercises.splice(i,1);renderExercises();updateCompletion()};const subBtn=card.querySelector('.substituteExercise');if(subBtn){const panel=card.querySelector('.sub-panel'),sel=card.querySelector('.sub-select'),manualWrap=card.querySelector('.sub-manual'),manual=card.querySelector('.sub-manual-input');subBtn.onclick=()=>{panel.classList.toggle('show');if(panel.classList.contains('show'))sel.focus()};sel.onchange=()=>{manualWrap.hidden=sel.value!=='__other__';if(sel.value==='__other__')manual.focus()};card.querySelector('.applySub').onclick=()=>applySubstitution(e,card);card.querySelector('.cancelSub').onclick=()=>panel.classList.remove('show');const restore=card.querySelector('.restoreExercise');if(restore)restore.onclick=()=>restoreOriginal(e)}})}
function activityTypeControl(e){if(!e.typeOptions?.length)return '';const opts=optionList(e.typeOptions,e.selectedType||'',`— select ${e.typeLabel||'type'} —`);return `<div class="activity-type"><label>${esc(e.typeLabel||'Activity type')}</label><select class="activityType">${opts}</select></div>`}
function exerciseHTML(e,i){const setRows=e.setData.map((s,si)=>`<div class="setrow"><b>${si+1}</b><select class="weight">${weightOptions(s.weight)}</select><select class="reps">${repOptions(s.reps)}</select><select class="time">${timeOptions(s.time)}</select><input class="notes" value="${esc(s.notes)}" placeholder="notes / band"></div>`).join('');return `<article class="exercise ${e.complete?'done':''}"><div class="exercise-head"><div class="num">${i+1}</div><div><h3>${esc(e.name)}</h3>${e.substitutedFor?`<div class="sub-badge">Substituted for ${esc(e.substitutedFor)}</div>`:''}<div class="rx">${e.setData.length} sets${e.reps?' · '+esc(e.reps):''}${e.time?' · '+esc(e.time):''}${e.rest?' · rest '+esc(e.rest):''}</div></div><div><label class="check"><input class="donecheck" type="checkbox" ${e.complete?'checked':''}> Mark all sets complete</label><div class="exercise-progress">${exerciseProgress(e).done}/${exerciseProgress(e).total} sets · ${exerciseProgress(e).percent}%</div></div></div><div class="exercise-grid"><div class="cuebox"><h4>Technique cue</h4><p>${esc(e.cue||'Use controlled repetitions and good form.')}</p></div><div class="cuebox"><h4>Alternative / note</h4><p>${esc(e.alt|| (e.custom?'Custom exercise':'Use the prescribed variation unless a substitution is needed.'))}</p></div></div>${activityTypeControl(e)}${!e.custom?`<div class="actions"><button class="small substituteExercise">${e.substitutedFor?'Change substitution':'Substitute exercise'}</button>${e.substitutedFor?'<button class="small restoreExercise">Restore original exercise</button>':''}</div><div class="sub-panel"><div class="sub-grid"><div><label>Replacement exercise</label><select class="sub-select">${substitutionOptions(e.substitutedFor?e.name:'')}</select></div><div class="sub-manual" hidden><label>Other exercise</label><input class="sub-manual-input" placeholder="Enter replacement name"></div><button class="small applySub">Apply substitution</button><button class="small cancelSub">Cancel</button></div><p class="muted">The replacement uses the same scheduled set slots, so completed sets receive full credit toward today’s workout. You may add or remove sets afterward.</p></div>`:''}<div class="sets"><div class="setlabels"><span>Set</span><span>Weight</span><span>Reps</span><span>Time</span><span>Notes</span></div>${setRows}<div class="setactions"><button class="small addset">+ Set</button><button class="small removeset">− Set</button>${e.custom?'<button class="small danger deleteExercise">Delete exercise</button>':''}</div></div></article>`}
function updateCompletion(){const p=workoutProgress({exercises:currentExercises});completionBar.style.width=p.percent+'%';completionText.textContent=`${p.done} of ${p.total} sets completed (${p.percent}%). Exercise checkboxes mark all sets complete.`;if(window.topCompletionBar)topCompletionBar.style.width=p.percent+'%';if(window.topCompletionText)topCompletionText.textContent=`${p.done} of ${p.total} sets · ${p.percent}%`;document.querySelectorAll('.exercise').forEach((card,i)=>{const ep=exerciseProgress(currentExercises[i]);const label=card.querySelector('.exercise-progress');if(label)label.textContent=`${ep.done}/${ep.total} sets · ${ep.percent}%`;card.classList.toggle('done',ep.percent===100)})}
function clearSessionFields(){totalMinutes.value='';rpe.value='';energyBefore.value='';energyAfter.value='';notes.value=''}
function recordId(day,date){return `${date}-${day}`}
function collect(){const d=PROGRAM[activeDay],date=workoutDate.value;return{id:recordId(d.day,date),date,day:d.day,focus:d.focus,plannedCount:d.ex.length,totalMinutes:totalMinutes.value,rpe:rpe.value,energyBefore:energyBefore.value,energyAfter:energyAfter.value,notes:notes.value,updatedAt:new Date().toISOString(),exercises:currentExercises.map(e=>({...e,setData:e.setData.map(s=>({...s}))}))}}
function save(silent=false){if(!workoutDate.value){alert('Choose a date.');return null}const rec=collect(),all=records(),idx=all.findIndex(x=>x.id===rec.id);if(idx>=0)all[idx]=rec;else all.push(rec);setRecords(all);renderDashboard();cloudUpsert(rec);if(!silent)alert((PROGRAM[activeDay].kind==='recovery'?'Recovery session':'Workout')+' saved locally'+(cloudUser?' and queued for cloud sync.':'.'));return rec;}
function loadSaved(show=true){const d=PROGRAM[activeDay],rec=records().find(x=>x.id===recordId(d.day,workoutDate.value));if(!rec){if(show)alert('No saved workout for this day and date.');return}currentExercises=normalizeSavedExercises(rec.exercises);totalMinutes.value=rec.totalMinutes||'';rpe.value=rec.rpe||'';energyBefore.value=rec.energyBefore||'';energyAfter.value=rec.energyAfter||'';notes.value=rec.notes||'';renderExercises();updateCompletion();if(show)alert('Saved workout loaded.');}
function clearForm(){if(!confirm('Clear the current unsaved form?'))return;currentExercises=baseExercises();clearSessionFields();renderExercises();updateCompletion()}
function addCustomExercise(form){const selected=form.querySelector('.customExercise').value;const manual=form.querySelector('.customName').value.trim();const name=selected==='__other__'?manual:selected;if(!name)return alert(selected==='__other__'?'Enter an exercise name.':'Select an exercise.');const setsEl=form.querySelector('.customSets'),weightEl=form.querySelector('.customWeight'),repsEl=form.querySelector('.customReps'),timeEl=form.querySelector('.customTime');const n=Math.max(1,+setsEl.value||1),weight=weightEl.value||'';currentExercises.push({id:'custom-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),custom:true,name,sets:n,reps:repsEl.value?repsEl.value:'',time:timeEl.value?timeEl.value+' sec':'',rest:'',cue:'Additional exercise — record the variation and form notes as needed.',complete:false,setData:Array.from({length:n},()=>({weight,reps:repsEl.value||'',time:timeEl.value||'',notes:''}))});form.querySelector('.customExercise').value='';form.querySelector('.customName').value='';form.querySelector('.manual-name').hidden=true;setsEl.value='2';weightEl.value='';repsEl.value='';timeEl.value='';renderExercises();updateCompletion();}
function weekStart(date){const d=new Date(date+'T12:00:00'),day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return d.toISOString().slice(0,10)}
function monthStart(){const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1).toISOString().slice(0,10)}
function filtered(){let r=records().sort((a,b)=>b.date.localeCompare(a.date));if(fromDate.value)r=r.filter(x=>x.date>=fromDate.value);if(toDate.value)r=r.filter(x=>x.date<=toDate.value);if(dayFilter.value)r=r.filter(x=>x.day===dayFilter.value);const p=periodFilter.value,t=isoToday();if(p==='week')r=r.filter(x=>x.date>=weekStart(t));if(p==='month')r=r.filter(x=>x.date>=monthStart());if(p==='12weeks'){const d=new Date();d.setDate(d.getDate()-84);r=r.filter(x=>x.date>=d.toISOString().slice(0,10))}return r}
function renderHistory(){const r=filtered(),done=r.reduce((n,x)=>n+workoutProgress(x).done,0),planned=r.reduce((n,x)=>n+workoutProgress(x).total,0),avg=planned?Math.round(done/planned*100):0,minutes=r.reduce((n,x)=>n+(+x.totalMinutes||0),0);historyStats.innerHTML=`<div class="stat"><span>Sessions logged</span><b>${r.length}</b></div><div class="stat"><span>Set completion</span><b>${avg}%</b></div><div class="stat"><span>Sets completed</span><b>${done}/${planned}</b></div><div class="stat"><span>Total minutes</span><b>${minutes}</b></div>`;historyList.innerHTML=r.length?r.map(x=>{const p=workoutProgress(x),performed=x.exercises.filter(e=>exerciseProgress(e).done>0);return `<div class="history-item"><div class="history-head"><div><h3>${esc(x.day)} · ${x.date}</h3><div class="history-meta">${esc(x.focus)} · ${p.done}/${p.total} sets (${p.percent}%)${x.totalMinutes?' · '+x.totalMinutes+' min':''}${x.rpe?' · RPE '+x.rpe:''}</div></div><div class="history-actions"><button class="small" onclick="openRecord('${x.id}')">Open</button><button class="small danger" onclick="deleteRecord('${x.id}')">Delete</button></div></div><div class="completed-list">${performed.map(e=>{const ep=exerciseProgress(e);return `<div><b>${esc(displayExerciseName(e))}</b> — ${ep.done}/${ep.total} sets (${ep.percent}%) · ${bestSummary(e)}</div>`}).join('')||'<div>No completed sets recorded.</div>'}</div>${x.notes?`<p><b>Notes:</b> ${esc(x.notes)}</p>`:''}</div>`}).join(''):'<div class="card empty">No workouts match these filters.</div>'}
function bestSummary(e){const vals=e.setData.filter(s=>s.weight||s.reps||s.time).map(s=>[s.weight&&`${s.weight} lb`,s.reps&&`${s.reps} reps`,s.time&&`${s.time} sec`].filter(Boolean).join(' · '));return vals.length?vals.join(' | '):'marked complete'}
window.openRecord=id=>{const rec=records().find(x=>x.id===id);activeDay=PROGRAM.findIndex(d=>d.day===rec.day);workoutDate.value=rec.date;$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view==='workout'));$$('.view').forEach(v=>v.classList.toggle('active',v.id==='workout'));renderWorkout(true);loadSaved(false);window.scrollTo({top:0,behavior:'smooth'})}
window.deleteRecord=id=>{if(!confirm('Delete this workout record?'))return;setRecords(records().filter(x=>x.id!==id));cloudDelete(id);renderHistory();renderDashboard()}
function exerciseNames(){const set=new Set();records().forEach(r=>r.exercises.forEach(e=>set.add(e.name)));PROGRAM.forEach(d=>d.ex.forEach(e=>set.add(e.name)));return [...set].sort()}
function renderProgress(){const weeks=+chartPeriod.value,all=records(),today=new Date(),data=[];for(let i=weeks-1;i>=0;i--){const d=new Date(today);d.setDate(d.getDate()-i*7);const ws=weekStart(d.toISOString().slice(0,10)),we=new Date(ws+'T12:00:00');we.setDate(we.getDate()+6);const week=all.filter(r=>r.date>=ws&&r.date<=we.toISOString().slice(0,10)),total=week.reduce((n,r)=>n+workoutProgress(r).total,0),done=week.reduce((n,r)=>n+workoutProgress(r).done,0),percent=total?Math.round(done/total*100):0;data.push({label:ws.slice(5),percent})}consistencyChart.innerHTML=data.map(x=>`<div class="barcol"><div class="barvalue">${x.percent}%</div><div class="bar" style="height:${Math.max(2,x.percent/100*185)}px"></div><div class="barlabel">${x.label}</div></div>`).join('');exerciseFilter.innerHTML=exerciseNames().map(n=>`<option ${n===exerciseFilter.value?'selected':''}>${esc(n)}</option>`).join('');renderExerciseProgress()}
function renderExerciseProgress(){const name=exerciseFilter.value;if(!name){exerciseProgress.innerHTML='<div class="empty">No exercises recorded yet.</div>';return}const rows=[];records().sort((a,b)=>a.date.localeCompare(b.date)).forEach(r=>r.exercises.filter(e=>e.name===name&&exerciseProgress(e).done>0).forEach(e=>{let maxWeight=0,maxReps=0,maxTime=0,volume=0;e.setData.filter(setHasData).forEach(s=>{const w=+s.weight||0,rep=parseFloat(s.reps)||0,t=parseFloat(s.time)||0;maxWeight=Math.max(maxWeight,w);maxReps=Math.max(maxReps,rep);maxTime=Math.max(maxTime,t);volume+=w*rep});rows.push({date:r.date,maxWeight,maxReps,maxTime,volume})}));exerciseProgress.innerHTML=rows.length?`<table class="progress-table"><thead><tr><th>Date</th><th>Max weight</th><th>Max reps</th><th>Max time</th><th>Volume</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.date}</td><td>${x.maxWeight||'—'}</td><td>${x.maxReps||'—'}</td><td>${x.maxTime||'—'}</td><td>${x.volume?Math.round(x.volume):'—'}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No completed records for this exercise yet.</div>'}
function exportData(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),records:records()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`strength-workout-backup-${isoToday()}.json`;a.click();URL.revokeObjectURL(a.href);backupStatus.textContent='Backup exported.'}
async function importDataFile(e){const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text()),incoming=Array.isArray(data)?data:data.records;if(!Array.isArray(incoming))throw new Error('Invalid backup file');const map=new Map(records().map(r=>[r.id,r]));incoming.forEach(r=>r?.id&&map.set(r.id,r));setRecords([...map.values()]); if(cloudUser) uploadAllLocal(); backupStatus.textContent=`Imported ${incoming.length} records.`}catch(err){backupStatus.textContent=err.message}e.target.value=''}
function init(){workoutDate.value=isoToday();activeDay=(new Date().getDay()+6)%7;PROGRAM.forEach(d=>dayFilter.insertAdjacentHTML('beforeend',`<option>${d.day}</option>`));nav();renderWorkout(true);renderDashboard();saveWorkout.onclick=save;loadWorkout.onclick=()=>loadSaved(true);clearWorkout.onclick=clearForm;markAllComplete.onclick=()=>markEveryExercise(true);markAllIncomplete.onclick=()=>markEveryExercise(false);$$('.custom-form').forEach(form=>{form.querySelector('.customExercise').innerHTML=customExerciseOptions();form.querySelector('.customExercise').onchange=()=>toggleManualName(form);form.querySelector('.customSets').innerHTML=setCountOptions('2');form.querySelector('.customWeight').innerHTML=weightOptions('');form.querySelector('.customReps').innerHTML=repOptions('');form.querySelector('.customTime').innerHTML=timeOptions('');form.querySelector('.addCustom').onclick=()=>addCustomExercise(form)});workoutDate.onchange=()=>loadSaved(false);applyFilters.onclick=renderHistory;resetFilters.onclick=()=>{fromDate.value='';toDate.value='';dayFilter.value='';periodFilter.value='all';renderHistory()};chartPeriod.onchange=renderProgress;exerciseFilter.onchange=renderExerciseProgress;exportData.onclick=exportData;importData.onchange=importDataFile;deleteAll.onclick=()=>{if(confirm('Permanently delete all locally stored workout data?')){localStorage.removeItem(KEY);backupStatus.textContent='All local data deleted.'}}}

let deferredInstallPrompt=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;installApp.hidden=false});
installApp?.addEventListener('click',async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;installApp.hidden=true});
window.addEventListener('appinstalled',()=>{installApp.hidden=true});
if('serviceWorker' in navigator && location.protocol.startsWith('http'))window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));


function cloudTimestamp(value){if(typeof value==='number')return value;if(value?.toMillis)return value.toMillis();const n=Date.parse(value||'');return Number.isFinite(n)?n:0}
function savedFirebaseConfig(){try{return JSON.parse(localStorage.getItem(FIREBASE_CONFIG_KEY)||'null')}catch{return null}}
function fillFirebaseConfig(){const c=savedFirebaseConfig()||{};fbApiKey.value=c.apiKey||'';fbAuthDomain.value=c.authDomain||'';fbProjectId.value=c.projectId||'';fbAppId.value=c.appId||'';fbStorageBucket.value=c.storageBucket||'';fbMessagingSenderId.value=c.messagingSenderId||''}
function configFromForm(){return {apiKey:fbApiKey.value.trim(),authDomain:fbAuthDomain.value.trim(),projectId:fbProjectId.value.trim(),appId:fbAppId.value.trim(),storageBucket:fbStorageBucket.value.trim(),messagingSenderId:fbMessagingSenderId.value.trim()}}
function setCloudStatus(state,text,detail=''){cloudDot.className='status-dot '+state;cloudStatus.textContent=text;cloudDetail.textContent=detail}
function renderCloudState(){if(!savedFirebaseConfig())return setCloudStatus('','Local only','Firebase is not configured.');if(!cloudUser)return setCloudStatus('','Cloud ready','Sign in to synchronize.');setCloudStatus('online','Synced account',cloudUser.email||'')}
async function initializeFirebase(){const config=savedFirebaseConfig();fillFirebaseConfig();if(!config?.apiKey||!config?.projectId||!config?.appId){renderCloudState();return}try{if(firebase.apps.length)firebaseApp=firebase.app();else firebaseApp=firebase.initializeApp(config);auth=firebase.auth();db=firebase.firestore();try{await db.enablePersistence({synchronizeTabs:true})}catch(e){if(!['failed-precondition','unimplemented'].includes(e.code))console.warn(e)}auth.onAuthStateChanged(handleAuthState);setCloudStatus('syncing','Cloud ready','Checking account…')}catch(err){setCloudStatus('error','Firebase error',friendlyFirebaseError(err));authMessage.textContent=friendlyFirebaseError(err)}}
function friendlyFirebaseError(err){return (err?.message||String(err)).replace(/^Firebase:\s*/,'').replace(/\s*\(auth\/[^)]+\)\.?$/,'')}
async function handleAuthState(user){cloudUser=user||null;signedOutPanel.hidden=!!user;signedInPanel.hidden=!user;if(user){signedInName.textContent=user.displayName||'Signed in';signedInEmail.textContent=user.email||'';authMessage.textContent='Your local records remain on this device and changes will synchronize automatically.';subscribeCloud();await mergeCloudOnce();await uploadAllLocal();renderCloudState();}else{if(cloudUnsubscribe){cloudUnsubscribe();cloudUnsubscribe=null}renderCloudState();}}
function cloudCollection(){return db.collection('users').doc(cloudUser.uid).collection('workouts')}
async function mergeCloudOnce(){if(!db||!cloudUser)return;setCloudStatus('syncing','Synchronizing','Downloading cloud history…');const snap=await cloudCollection().get();const map=new Map(records().map(r=>[r.id,r]));snap.forEach(doc=>{const remote=doc.data(),local=map.get(remote.id);if(!local||cloudTimestamp(remote.updatedAt)>cloudTimestamp(local.updatedAt))map.set(remote.id,remote)});cloudApplying=true;setRecords([...map.values()]);cloudApplying=false;renderDashboard();renderHistory();renderProgress();}
function subscribeCloud(){if(cloudUnsubscribe)cloudUnsubscribe();cloudUnsubscribe=cloudCollection().onSnapshot(snap=>{let changed=false;const map=new Map(records().map(r=>[r.id,r]));snap.docChanges().forEach(ch=>{const remote=ch.doc.data();if(ch.type==='removed'){if(map.delete(ch.doc.id))changed=true}else{const local=map.get(remote.id);if(!local||cloudTimestamp(remote.updatedAt)>cloudTimestamp(local.updatedAt)){map.set(remote.id,remote);changed=true}}});if(changed){cloudApplying=true;setRecords([...map.values()]);cloudApplying=false;renderDashboard();renderHistory();renderProgress();const selected=map.get(recordId(PROGRAM[activeDay].day,workoutDate.value));if(selected)loadSaved(false)}renderCloudState()},err=>setCloudStatus('error','Sync error',friendlyFirebaseError(err)))}
async function cloudUpsert(rec){if(!db||!cloudUser)return;try{setCloudStatus('syncing','Synchronizing','Saving '+rec.date+'…');await cloudCollection().doc(rec.id).set(rec,{merge:true});renderCloudState()}catch(err){setCloudStatus('error','Sync error',friendlyFirebaseError(err))}}
async function cloudDelete(id){if(!db||!cloudUser)return;try{await cloudCollection().doc(id).delete();renderCloudState()}catch(err){setCloudStatus('error','Sync error',friendlyFirebaseError(err))}}
async function uploadAllLocal(){if(!db||!cloudUser)return;const all=records();setCloudStatus('syncing','Synchronizing',`Uploading ${all.length} records…`);const batches=[];for(let i=0;i<all.length;i+=400)batches.push(all.slice(i,i+400));for(const chunk of batches){const batch=db.batch();chunk.forEach(r=>{if(!r.updatedAt)r.updatedAt=new Date().toISOString();batch.set(cloudCollection().doc(r.id),r,{merge:true})});await batch.commit()}renderCloudState();authMessage.textContent=`Synchronized ${all.length} local records.`}
function setupCloudUI(){fillFirebaseConfig();saveFirebaseConfig.onclick=()=>{const c=configFromForm();if(!c.apiKey||!c.authDomain||!c.projectId||!c.appId)return authMessage.textContent='API key, auth domain, project ID, and app ID are required.';localStorage.setItem(FIREBASE_CONFIG_KEY,JSON.stringify(c));location.reload()};clearFirebaseConfig.onclick=()=>{if(confirm('Remove Firebase configuration from this browser? Local workout data will remain.')){localStorage.removeItem(FIREBASE_CONFIG_KEY);location.reload()}};googleSignIn.onclick=async()=>{if(!auth)return authMessage.textContent='Save a Firebase configuration first.';try{await auth.signInWithPopup(new firebase.auth.GoogleAuthProvider())}catch(e){authMessage.textContent=friendlyFirebaseError(e)}};emailSignIn.onclick=async()=>{try{await auth.signInWithEmailAndPassword(authEmail.value.trim(),authPassword.value)}catch(e){authMessage.textContent=friendlyFirebaseError(e)}};emailCreate.onclick=async()=>{try{await auth.createUserWithEmailAndPassword(authEmail.value.trim(),authPassword.value)}catch(e){authMessage.textContent=friendlyFirebaseError(e)}};passwordReset.onclick=async()=>{try{await auth.sendPasswordResetEmail(authEmail.value.trim());authMessage.textContent='Password-reset email sent.'}catch(e){authMessage.textContent=friendlyFirebaseError(e)}};signOut.onclick=()=>auth?.signOut();syncNow.onclick=async()=>{await mergeCloudOnce();await uploadAllLocal()};uploadLocal.onclick=uploadAllLocal;initializeFirebase()}

setupCloudUI();
init();

function clearAllSetEntries(){
  if(!confirm('Clear all set entries and exercise checks for this workout?')) return;
  currentExercises.forEach(e=>{e.complete=false;e.setData.forEach(x=>{x.weight='';x.reps='';x.time='';x.notes=''})});
  renderExercises();
}
function showSimpleSummary(){
  const rec=save(true); if(!rec) return;
  const p=workoutProgress(rec);
  const volume=Math.round(rec.exercises.reduce((n,e)=>n+exerciseBest(e).volume,0));
  completionSummary.innerHTML=`<b>Workout saved.</b> ${p.done} of ${p.total} sets completed (${p.percent}%). ${rec.totalMinutes?`${rec.totalMinutes} minutes recorded. `:''}${volume?`${volume.toLocaleString()} total logged volume.`:''}`;
  completionSummary.classList.add('show');
  completionSummary.scrollIntoView({behavior:'smooth',block:'nearest'});
  renderDashboard();
}

document.getElementById('startToday').onclick=()=>{const d=new Date();workoutDate.value=isoToday();activeDay=(d.getDay()+6)%7;renderWorkout(true);loadSaved(false);window.scrollTo({top:0,behavior:'smooth'});};
document.getElementById('markAllSets').onclick=()=>markEveryExercise(true);
document.getElementById('clearAllSets').onclick=clearAllSetEntries;
document.getElementById('finishWorkout').onclick=showSimpleSummary;
